import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { NavLink } from "@/hooks/NavLink";
import { AuthProvider } from "@/components/AuthContext";
import AuthButtons from "@/components/AuthButtons";
import UserStatus from "@/components/UserStatus";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <header style={{ height: 150, borderBottom: "1px solid #ccc" }}>
          <nav style={{ padding: "10px 0" }}>
              <UserStatus/>
              <AuthButtons />
            <ul style={{ listStyle: "none", display: "flex", gap: 20 }}>
              <li><NavLink href={"/"}>Home</NavLink></li>
              <li><NavLink href={"/about"}>About</NavLink></li>
              <li><NavLink href={"/posts"}>Posts</NavLink></li>
              <li><NavLink href="/create-post">New Post</NavLink></li>
              <li><NavLink href="/dashboard">Dashboard</NavLink></li>
              <li><NavLink href="/sceleton-list">Sceleton</NavLink></li>

            </ul>
          </nav>
        </header>
        <main>
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
