import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { NavLink } from "@/hooks/NavLink";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav style={{ padding: "10px 0", borderBottom: "1px solid #ccc" }}>
            <ul style={{ listStyle: "none", display: "flex", gap: 20 }}>
              <li><NavLink href={"/"}>Home</NavLink></li>
              <li><NavLink href={"/about"}>About</NavLink></li>
              <li><NavLink href={"/posts"}>Posts</NavLink></li>
              <li><NavLink href="/new-post">New Post</NavLink></li>
            </ul>
          </nav>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
